# Generated by Django 4.2.6 on 2023-10-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("car_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="car_store.cartype",
            ),
        ),
        migrations.AlterField(
            model_name="cartype",
            name="brand",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="cartype",
            name="model",
            field=models.CharField(max_length=20),
        ),
    ]
